language: node_js
node_js:
  - node
os:
  - linux
cache:
  directories:
  - node_modules
env:
  global:
    - CI: false   # otherwise build will fail if there are warnings
  jobs:
    - S3_BUCKET: react-redux-would-you-rather
jobs:
  include:
    - stage: test
      install:
        - npm install
      script:
        - npm test
    - stage: build
      install: skip
      script: 
        - npm run build
    - stage: deploy
      install: skip
      script: skip
      deploy:
        provider: s3
        access_key_id: $ACCESS_KEY_ID
        secret_access_key: $SECRET_ACCESS_KEY
        local_dir: build
        bucket: $S3_BUCKET
        cleanup: true
        region: "ap-southeast-2"
        on:
        #   branch: master
          all_branches: true